"""Add name and subtitle to Banner

Revision ID: 044e5d1e7a71
Revises: dea12f3eb8d3
Create Date: 2025-11-18 15:35:33.034639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044e5d1e7a71'
down_revision = 'dea12f3eb8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_column('subtitle')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
